FROM centos:centos7
LABEL org.opencontainers.image.authors="githubfoam"


RUN yum update -qy && yum install \
    gcc \
    tcpdump -yq

RUN mkdir /home/vagrant && \
    # create a user ‘builder‘ with home directory ‘/home/vagrant‘, 
    # default shell /bin/bash and adds extra information about user
    useradd -m -d /home/vagrant -s /bin/bash -c "builder" -U vagrant  && \
    chown -R vagrant /home/vagrant

USER vagrant

WORKDIR /tmp