# Converting from CentOS Linux 8 to CentOS Stream 8
# https://www.centos.org/centos-stream/
FROM centos:centos8 AS centos-convert

LABEL org.opencontainers.image.authors="githubfoam"

# verify centos 8 
RUN cat /etc/os-release && \ 
    dnf install centos-release-stream -yq && \
    dnf swap centos-{linux,stream}-repos -yq && \
    dnf distro-sync -yq && \
    dnf clean all

FROM centos-convert AS stream-base

# verify centos stream 
RUN cat cat /etc/os-release
    

CMD ["/bin/bash"]

