FROM centos:centos8
LABEL org.opencontainers.image.authors="githubfoam"


RUN yum update -qy && yum install \
    gcc \
    tcpdump -yq

# Create user and set ownership and permissions as required
RUN mkdir myapp-data && adduser -D myuser && chown -R myuser /myapp-data

USER myuser

WORKDIR /tmp