# https://hub.docker.com/r/arm64v8/centos/
FROM centos:centos8 AS centos-convert

LABEL org.opencontainers.image.authors="githubfoam"


RUN dnf -y install centos-release-stream && \
    dnf -y swap centos-{linux,stream}-repos && \
    dnf -y distro-sync && \
    dnf clean all

FROM centos-convert AS stream-base

RUN cat /etc/system-release && \
    cat /etc/os-release

CMD ["/bin/bash"]

