name: "podman centos  CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-latest-manual-build-apache-podman-job:
    name: "podman manual build apache docker centos ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch 
    - name: "build manual docker"
      run: sudo make deploy-manual-build-apache-podman  



