name: "centos stream CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  # ubuntu-latest-manual-build-job:
  #   name: "manual build docker centos ubuntu-latest"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: |
  #       hostnamectl status
  #       lsb_release -a
  #       lsb_release -d
  #       cat /etc/lsb-release
  #       cat /etc/issue
  #       cat /etc/os-release
  #       sudo apt-get install -y neofetch && neofetch 
  #   - name: "build manual docker"
  #     run: sudo make deploy-manual-build     



  ubuntu-latest-centos-stream-single-job:
    name: "centos-stream docker image ubuntu-latest"
    runs-on: ubuntu-latest
    env:
      distribution: "centos" #https://hub.docker.com/_/centos
      version: "latest"
      name: "centos/stream"
      dockerfiledir: "dockerfiles"  
      dockerfilename: "Dockerfile.centos.stream"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch 
    - name: "docker build centos stream"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename} 
        docker image ls
        docker image history ${name}:${version}
        docker system df -v               
        docker image inspect ${name}:${version}        

  ubuntu-latest-centos-stream-multi-job:
    name: "centos-stream docker image ubuntu-latest"
    runs-on: ubuntu-latest
    env:
      distribution: "centos" #https://hub.docker.com/_/centos
      version: "latest"
      name: "centos/stream"
      dockerfiledir: "dockerfiles"  
      dockerfilename: "Dockerfile.centos.multi"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch 
    - name: "docker build centos stream"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename} 
        docker image ls
        docker image history ${name}:${version}
        docker system df -v               
        docker image inspect ${name}:${version}  

  ubuntu-latest-centos-stream-python3-job:
    name: "centos-stream docker image ubuntu-latest"
    runs-on: ubuntu-latest
    env:
      distribution: "centos" #https://hub.docker.com/_/centos
      version: "latest"
      name: "centos/stream"
      dockerfiledir: "dockerfiles"  
      dockerfilename: "Dockerfile.centos.python3"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch 
    - name: "docker build centos stream"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename} 
        docker image ls
        docker image history ${name}:${version}
        docker system df -v               
        docker image inspect ${name}:${version} 

