name: "whatwaf centos CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-snort-source-latest-job:
    name: "whatwaf source centos docker ubuntu latest"
    runs-on: ubuntu-latest
    env:
      version: "latest"
      name: "centos/whatwaf"
      dockerfilename: "centos.stream8.multi.python3.whatwaf"
      dockerfiledir: "dockerfiles"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "docker build centos snort"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename}  
        docker image ls
        docker image history ${name}:${version}
        docker system df -v               
        docker image inspect ${name}:${version}    
